name: Build and push container to registry
run-name: ${{ gitea.actor }} is building project 🚀
on:
  workflow_dispatch:
    inputs:
      push_to_github:
        description: 'Also push to GitHub Container Registry'
        required: false
        default: false
        type: boolean
      custom_tags:
        # Comma-separated list of tags to push (e.g., "v1.2,v1.2.1,latest")
        description: 'Custom tags for the image (comma-separated, e.g., v1.2,v1.2.1)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build image
        env:
          REPOSITORY_IMAGE: ${{ vars.REPOSITORY_IMAGE }}
        run: docker compose -f docker/docker-compose.build.yml build traefik-configurator
      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: Push image to Gitea Container Registry
        env:
          REPOSITORY_IMAGE: ${{ vars.REPOSITORY_IMAGE }}
        run: docker compose -f docker/docker-compose.build.yml push traefik-configurator
      - name: Login to GitHub Container Registry
        if: ${{ github.event.inputs.push_to_github == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Tag and push to GitHub Container Registry
        if: ${{ github.event.inputs.push_to_github == 'true' }}
        env:
          REPOSITORY_IMAGE: ${{ vars.REPOSITORY_IMAGE }}
          REPOSITORY_IMAGE_PUBLIC: ${{ vars.REPOSITORY_IMAGE_PUBLIC }}
        run: |
          # Get the image name from the built image
          SOURCE_IMAGE="${REPOSITORY_IMAGE}"
          TARGET_IMAGE="${REPOSITORY_IMAGE_PUBLIC}"
          
          # Tag the image for GitHub
          docker tag "${SOURCE_IMAGE}" "${TARGET_IMAGE}"
          
          # Push to GitHub
          docker push "${TARGET_IMAGE}"
      - name: Tag and push custom tags to GitHub Container Registry
        if: ${{ github.event.inputs.push_to_github == 'true' && github.event.inputs.custom_tags != '' }}
        env:
          REPOSITORY_IMAGE: ${{ vars.REPOSITORY_IMAGE }}
          REPOSITORY_IMAGE_PUBLIC: ${{ vars.REPOSITORY_IMAGE_PUBLIC }}
          CUSTOM_TAGS: ${{ github.event.inputs.custom_tags }}
        run: |
          # Get the base image name from REPOSITORY_IMAGE_PUBLIC (remove any existing tag)
          BASE_IMAGE=$(echo "${REPOSITORY_IMAGE_PUBLIC}" | cut -d':' -f1)

          # Split comma-separated tags and push each
          IFS=',' read -ra TAGS <<< "${CUSTOM_TAGS}"
          for TAG in "${TAGS[@]}"; do
            TAG=$(echo "$TAG" | xargs)  # Trim whitespace
            if [ -n "$TAG" ]; then
              echo "Tagging and pushing: ${BASE_IMAGE}:${TAG}"
              docker tag "${REPOSITORY_IMAGE}" "${BASE_IMAGE}:${TAG}"
              docker push "${BASE_IMAGE}:${TAG}"
            fi
          done
      - name: Create build metadata
        run: |
          cat > build-metadata.json << EOF
          {
            "pushed_to_github": "${{ github.event.inputs.push_to_github || 'false' }}",
            "custom_tags": "${{ github.event.inputs.custom_tags || '' }}"
          }
          EOF
      - name: Upload build metadata
        uses: https://github.com/Janhouse/gitea-upload-artifact@v4
        with:
          name: build-metadata
          path: build-metadata.json
          retention-days: 1
