name: Build and push container to registry
run-name: ${{ gitea.actor }} is building project 🚀
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build image
        env:
          REPOSITORY_IMAGE: ${{ vars.REPOSITORY_IMAGE }}
        run: docker compose -f docker/docker-compose.build.yml build traefik-configurator
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: Push image
        env:
          REPOSITORY_IMAGE: ${{ vars.REPOSITORY_IMAGE }}
        run: docker compose -f docker/docker-compose.build.yml push traefik-configurator
